### ISSUE TITLE
visual error in replay viewer

### ISSUE THREAD

**Issue by CamillaLee** [unhappychoice/ReplayMod#10]
replay viewer doesn't render blocks properly...

Hi... I thought I've solve the problem but it happend again... TAT
Can you please help me?

[latest.log](https://github.com/unhappychoice/ReplayMod/files/6716591/latest.log)

**Comment by unhappychoice** [comment]
Does this happen another record?

```
[256¿ù2021 22:41:01.496] [Thread-37/ERROR] [com.replaymod.replay.ReplayModReplay/]: Could not load Replay File 2021_05_29_19_31_32.mcpr
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_291]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_291]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_291]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_291]
	at com.replaymod.replaystudio.replay.ZipReplayFile.<init>(ZipReplayFile.java:102) ~[replaymod:?]
	at com.replaymod.core.ReplayMod.openReplay(ReplayMod.java:436) ~[replaymod:?]
	at com.replaymod.core.ReplayMod.openReplay(ReplayMod.java:428) ~[replaymod:?]
	at com.replaymod.replay.gui.screen.GuiReplayViewer$GuiReplayList.lambda$new$3(GuiReplayViewer.java:373) ~[replaymod:?]
	at com.replaymod.gui.element.advanced.AbstractGuiResourceLoadingList$1.run(AbstractGuiResourceLoadingList.java:119) [replaymod:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
```

means failing to record a replay file

**Comment by CamillaLee** [comment]
now it happens all the time 8-8... 
I'll leave you another latest log file

[latest.log](https://github.com/unhappychoice/ReplayMod/files/6719433/latest.log)

**Comment by unhappychoice** [comment]
```
[266¿ù2021 10:37:49.129] [Render thread/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	buildinggadgets:construction_block: 16414
	buildinggadgets:construction_block_dense: 16415
	buildinggadgets:construction_block_powder: 16416
	buildinggadgets:effect_block: 16413
	buildinggadgets:template_manager: 16417

[266¿ù2021 10:37:49.130] [Render thread/WARN] [net.minecraftforge.registries.GameData/REGISTRIES]: Forge Mod Loader detected missing registry entries.

There are 5 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.


[266¿ù2021 10:37:49.130] [Render thread/WARN] [net.minecraftforge.registries.GameData/REGISTRIES]: Missing minecraft:block:
    buildinggadgets:construction_block
    buildinggadgets:construction_block_dense
    buildinggadgets:construction_block_powder
    buildinggadgets:effect_block
    buildinggadgets:template_manager
```

means you removed the mod `building gadgets`
I don't support changing mod list after creating the world
