### ISSUE TITLE
Crashing randomly whilst using console commands when playing world normally 1.16.5

### ISSUE THREAD

**Issue by NighthowlerStudios** [unhappychoice/ReplayMod#28]
crashes like these can occur anytime the enter key is pressed to close a gui or the console, usually whilst the game is trying to accept input into the chat/commands.  it is a client side only crash.  to reproduce, spam any command until the client crashes.

Description: keyPressed event handler

java.lang.ArrayIndexOutOfBoundsException: 242
	at net.minecraftforge.eventbus.ListenerList.unregister(ListenerList.java:133) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.ListenerList.unregisterAll(ListenerList.java:140) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.unregister(EventBus.java:277) ~[eventbus-4.0.0.jar:?] {}
	at com.replaymod.gui.utils.EventRegistrations.unregister(EventRegistrations.java:33) ~[?:?] {re:classloading}
	at com.replaymod.gui.container.VanillaGuiScreen$EventHandler.onGuiClosed(VanillaGuiScreen.java:123) ~[?:?] {re:classloading,pl:eventbus:A}
	at com.replaymod.gui.container.VanillaGuiScreen$EventHandler.lambda$new$0(VanillaGuiScreen.java:119) ~[?:?] {re:classloading,pl:eventbus:A}
	at com.replaymod.gui.container.VanillaGuiScreen$EventHandler$$Lambda$13907/1728758279.openGuiScreen(Unknown Source) ~[?:?] {}
	at com.replaymod.gui.versions.callbacks.OpenGuiScreenCallback.lambda$null$0(OpenGuiScreenCallback.java:10) ~[?:?] {re:classloading}
	at com.replaymod.gui.versions.callbacks.OpenGuiScreenCallback$$Lambda$13906/1047339359.openGuiScreen(Unknown Source) ~[?:?] {}
	at com.replaymod.gui.versions.forge.EventsAdapter.onGuiClosed(EventsAdapter.java:38) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_455_EventsAdapter_onGuiClosed_GuiOpenEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2971/883669350.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}

**Comment by NighthowlerStudios** [comment]
Seems to be a mod conflict somewhere down the chain as even after removal a similar crash occured.
