### ISSUE TITLE
ReplayMod stuck in a loop while loading replays

### ISSUE THREAD

**Issue by zipstie** [unhappychoice/ReplayMod#7]
So when I try to load my replay, it gets stuck looping between the "Loading Terrain" screen and a blank screen. When looking at the log you can tell it's stuck in a loop, however, I'm not sure which mod is causing this. The game never crashes, so there's no crash log.
[latest.txt](https://github.com/unhappychoice/ReplayMod/files/6681141/latest.txt)

**Comment by unhappychoice** [comment]
Try create another replay record and view that.
And if you still have the problem, paste entire `lastest.log` including recording sequence

**Comment by zipstie** [comment]
Sorry, I forgot about this. 
So for this log, I joined the server, recorded for about 4 minutes, stoped/saved the recording, and tried to load it. Again when I tried to load it, it got stuck in the same loop of "Loading Terrain" and a black screen.
[latest.log](https://github.com/unhappychoice/ReplayMod/files/6744129/latest.log)

**Comment by unhappychoice** [comment]
The lastest release may help https://github.com/unhappychoice/ReplayMod/releases/tag/1.0.0
But I may need investigate

**Comment by zipstie** [comment]
Downloaded the new version and reinstalled JEI. When I create a single-player world, I can record and load the replay. However, when I join the server and try to load the replay, it gets stuck in the loop. When I uninstall JEI, join the server, and try to load the replay it still gets stuck in the loop

**Comment by BraveCaperCat** [comment]
It will make a lot more sense if you renamed it to:
Replay mod is stuck on loading terrain on servers

**Comment by BaronDuScotch** [comment]
it seems this issue was not fixed yet. I have exactly the same thing: in solo everything works just fine, but when i record on a server and try to open the file in the editor, it gets stuck in a loading loop, but it doesn't crash...
this the error in the game output before it start looping:
15:34:51.497
[15:34:51] [Thread-24/ERROR] [co.re.re.ReplayModReplay/]: Could not load Replay File 2022_08_31_23_33_18.mcpr
15:34:51.497
java.util.zip.ZipException: error in opening zip file
15:34:51.497
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51] {}
15:34:51.497
at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51] {}
15:34:51.497
at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51] {}
15:34:51.497
at java.util.zip.ZipFile.<init>(ZipFile.java:164) ~[?:1.8.0_51] {}
15:34:51.497
at com.replaymod.replaystudio.replay.ZipReplayFile.<init>(ZipReplayFile.java:102) ~[?:?] {re:classloading}
15:34:51.498
at com.replaymod.core.ReplayMod.openReplay(ReplayMod.java:407) ~[?:?] {re:mixin,re:classloading}
15:34:51.498
at com.replaymod.core.ReplayMod.openReplay(ReplayMod.java:399) ~[?:?] {re:mixin,re:classloading}
15:34:51.498
at com.replaymod.replay.gui.screen.GuiReplayViewer$GuiReplayList.lambda$new$3(GuiReplayViewer.java:358) [?:?] {re:classloading}
15:34:51.498
at com.replaymod.replay.gui.screen.GuiReplayViewer$GuiReplayList$$Lambda$22218/1114508498.consume(Unknown Source) [?:?] {}
15:34:51.498
at com.replaymod.gui.element.advanced.AbstractGuiResourceLoadingList$1.run(AbstractGuiResourceLoadingList.java:114) [?:?] {re:classloading}
15:34:51.498
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
