### ISSUE TITLE
I dont know where to send this but I saw on reddit I should place it here on github but i dont know where(my game is crashing when i load a video))

### ISSUE THREAD

**Issue by Jexiplier** [unhappychoice/ReplayMod#8]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 6/21/21 6:49 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.multiplayer.PlayerController.func_78750_j(PlayerController.java:252) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:APP:mixins.replaymod.json:Mixin_PlayerControllerMP,pl:mixin:APP:mixins.baritone.json:MixinPlayerController,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_78765_e(PlayerController.java:232) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:APP:mixins.replaymod.json:Mixin_PlayerControllerMP,pl:mixin:APP:mixins.baritone.json:MixinPlayerController,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1426) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.30.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.30.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.multiplayer.PlayerController.func_78750_j(PlayerController.java:252) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:APP:mixins.replaymod.json:Mixin_PlayerControllerMP,pl:mixin:APP:mixins.baritone.json:MixinPlayerController,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_78765_e(PlayerController.java:232) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:APP:mixins.replaymod.json:Mixin_PlayerControllerMP,pl:mixin:APP:mixins.baritone.json:MixinPlayerController,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 441, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:mixins.replaymod.json:MixinWorldClient,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.30.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.30.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1323285232 bytes (1261 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	CPUs: 4
	JVM Flags: 6 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.30
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |DONE      |Manifest: NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |Manifest: NOSIGNATURE
		platforms-1.16-1.7.11.jar                         |Platforms                     |platforms                     |1.7.11              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.5.1.jar                        |Waystones                     |waystones                     |7.5.1               |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.24.jar                               |Clumps                        |clumps                        |6.0.0.24            |DONE      |Manifest: NOSIGNATURE
		modernlife-1.16.5-1.12.jar                        |Modern Life                   |modernlife                    |1.16.5-1.12         |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.2.jar                |Traveler's Backpack           |travelersbackpack             |5.4.2               |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		ClassicCombat-1.16.4-universal.jar                |Classic Combat                |classiccombat                 |1.0                 |DONE      |Manifest: NOSIGNATURE
		FarmingForBlockheads_1.16.5-7.3.1.jar             |Farming for Blockheads        |farmingforblockheads          |7.3.1               |DONE      |Manifest: NOSIGNATURE
		mapperbase-1.16.4-2.3.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |Manifest: NOSIGNATURE
		sworddisplay-1.16.5-1.2.0.jar                     |Sword Displays                |sworddisplay                  |1.16.5-1.2.0        |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		AdPother-1.16.4-4.0.4.0-build.0124.jar            |Pollution of the Realms       |adpother                      |4.0.4.0             |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-4.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-4             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.30-universal.jar                |Forge                         |forge                         |36.1.30             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		shetiphiancore-1.16-3.8.5.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.5               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.490-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.30-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.0.4.171.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.171           |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.3.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.3        |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.0-135.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.0-135    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.103.jar                         |Mantle                        |mantle                        |1.6.103             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.9.0.1_Forge_1.16.5.jar          |Xaero's Minimap               |xaerominimap                  |21.9.0.1            |DONE      |Manifest: NOSIGNATURE
		roadstuff-1.16.4-4.2.0.jar                        |Road Stuff                    |roadstuff                     |1.16.4-4.2.0        |DONE      |Manifest: NOSIGNATURE
		replaymod-1.16.4-forge-1.0.0-beta3.jar            |Replay Mod                    |replaymod                     |2.5.1               |DONE      |Manifest: NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.8.21.1.jar              |SecurityCraft                 |securitycraft                 |v1.8.21.1           |DONE      |Manifest: NOSIGNATURE
		BetterDiving-1.16.5-1.2.3.jar                     |Better Diving                 |better_diving                 |1.2.3               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		OfflineSkins-1.16.5-v2.jar                        |OfflineSkins                  |offlineskins                  |1.16.5-v2           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.16.5-20210517a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210517a    |DONE      |Manifest: NOSIGNATURE
		MarketCrates-1.16.4-35.1.4-v1.1-universal.jar     |Market Crates                 |marketcrates                  |v1.1-universal      |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		modular-routers-1.16.5-7.4.0-55.jar               |Modular Routers               |modularrouters                |task ':jar' property|DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.16.4-6.0.10.0-build.0125.jar         |Advanced Chimneys             |adchimneys                    |6.0.10.0            |DONE      |Manifest: NOSIGNATURE
		baritone-standalone-forge-1.6.3.jar               |Baritone                      |baritoe                       |1.6.3               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.4-3.5.1.408-universal.jar     |CodeChicken Lib               |codechickenlib                |3.5.1.408           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.4-2.7.1.166-universal.jar       |EnderStorage                  |enderstorage                  |2.7.1.166           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		lumberjack-2.1.4.jar                              |LumberJack                    |lumberjack                    |2.1.4               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5b7e0e69-5539-4161-a85a-210f14eaa331
	Launched Version: 1.16.5-forge-36.1.30
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.11
	OpenGlRenderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by unhappychoice** [comment]
Remove baritone
